import { describe, it, expect } from 'vitest';
import { generateServer } from './server.js';
import type { LanguageDefinition } from '../definition/index.js';

/** Minimal language definition for testing */
function createTestDefinition(): LanguageDefinition<'program' | 'identifier'> {
  return {
    name: 'TestLang',
    fileExtensions: ['.test'],
    entry: 'program',
    word: 'identifier',
    grammar: {
      program: r => r.repeat(r.rule('identifier')),
      identifier: r => r.token(/[a-z]+/),
    },
  };
}

describe('generateServer', () => {
  it('generates non-empty output', () => {
    const result = generateServer(createTestDefinition());
    expect(result.length).toBeGreaterThan(0);
  });

  it('includes generated-by header', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('LSP server for TestLang');
    expect(result).toContain('Generated by treelsp');
    expect(result).toContain('do not edit');
  });

  it('imports vscode-languageserver', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain("from 'vscode-languageserver/node'");
    expect(result).toContain('createConnection');
    expect(result).toContain('TextDocuments');
    expect(result).toContain('ProposedFeatures');
    expect(result).toContain('TextDocumentSyncKind');
    expect(result).toContain('DiagnosticSeverity');
  });

  it('imports vscode-languageserver-textdocument', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain("from 'vscode-languageserver-textdocument'");
    expect(result).toContain('TextDocument');
  });

  it('imports treelsp runtime', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain("from 'treelsp/runtime'");
    expect(result).toContain('createServer');
    expect(result).toContain('createDocumentState');
  });

  it('imports language definition from grammar.js', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain("from '../grammar.js'");
  });

  it('sets up connection and text documents', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('createConnection(ProposedFeatures.all)');
    expect(result).toContain('new TextDocuments(TextDocument)');
  });

  it('resolves grammar WASM path', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain("resolve(__dirname, 'grammar.wasm')");
    expect(result).toContain('fileURLToPath');
  });

  it('creates language service', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('createServer(definition)');
  });

  it('uses lowercase language ID', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain("languageId: 'testlang'");
  });

  it('declares server capabilities', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('onInitialize');
    expect(result).toContain('textDocumentSync: TextDocumentSyncKind.Full');
    expect(result).toContain('hoverProvider: true');
    expect(result).toContain('definitionProvider: true');
    expect(result).toContain('referencesProvider: true');
    expect(result).toContain('completionProvider');
    expect(result).toContain('renameProvider: true');
    expect(result).toContain('documentSymbolProvider: true');
  });

  it('handles document lifecycle', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('onDidOpen');
    expect(result).toContain('onDidChangeContent');
    expect(result).toContain('onDidClose');
  });

  it('wires LSP handlers', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('connection.onHover');
    expect(result).toContain('connection.onDefinition');
    expect(result).toContain('connection.onReferences');
    expect(result).toContain('connection.onCompletion');
    expect(result).toContain('connection.onRenameRequest');
    expect(result).toContain('connection.onDocumentSymbol');
  });

  it('maps diagnostic severity', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('DiagnosticSeverity.Error');
    expect(result).toContain('DiagnosticSeverity.Warning');
    expect(result).toContain('DiagnosticSeverity.Information');
    expect(result).toContain('DiagnosticSeverity.Hint');
  });

  it('sends diagnostics with language source', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain("d.source ?? 'testlang'");
  });

  it('disposes document states on close', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('state.dispose()');
    expect(result).toContain('documentStates.delete');
  });

  it('starts listening', () => {
    const result = generateServer(createTestDefinition());
    expect(result).toContain('textDocuments.listen(connection)');
    expect(result).toContain('connection.listen()');
  });

  it('uses language name in server header', () => {
    const def = createTestDefinition();
    def.name = 'MyCustomLang';
    const result = generateServer(def);
    expect(result).toContain('LSP server for MyCustomLang');
    expect(result).toContain("languageId: 'mycustomlang'");
  });
});
